language: python

python:
  - '3.6.1'

install:
  - pip install -r requirements.txt

deploy:
  provider: heroku

  buildpack: python

  api_key:
    secure: d89da968-a04e-4feb-b8e4-3e3913b03eaa

  strategy: git

  app: whispering-castle-35269

  on:
    repo: mikuspikus/webapp-example

  run:
    - "python manage.py migrate"
    - restart

script: 
  - python manage.py test
